source "https://rubygems.org"

gem "pg"
gem "autoforme"
gem "sequel"
gem "sequel_pg"
gem "sequel_postgresql_triggers"
gem "roda"
gem "tilt"
gem "rack-protection"
gem "sinatra-flash"
gem "bcrypt-ruby"
gem "rack_csrf"
gem "thamble"
gem "unicorn"
